# Generated by Django 4.2.7 on 2023-11-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20)),
                ('fecha_compra', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=50)),
                ('jefe_departamento', models.CharField(max_length=100)),
                ('ubicacion_departamento', models.CharField(max_length=100)),
                ('telefono_departamento', models.CharField(max_length=20)),
                ('numero_empleados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=50)),
                ('especialidad_medico', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('años_experiencia', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('responsable_sucursal', models.CharField(max_length=100)),
                ('ubicacion_sucursal', models.CharField(max_length=100)),
                ('telefono_sucursal', models.CharField(max_length=20)),
                ('horario_atencion', models.DateField()),
            ],
        ),
    ]
